import React from 'react'
import { DataTable } from './components/data-table'
import { columns, User } from './components/columns'
const testUsers: User[] = [
  {
    id: "1",
    qrCode: "QR001",
    firstName: "Alice",
    lastname: "Johnson",
    email: "alice.johnson@example.com",
    role: "Manager",
    status: "Active",
    agency: "Agency A",
    department: "HR",
    dateHired: "2021-03-15",
  },
  {
    id: "2",
    qrCode: "QR002",
    firstName: "Bob",
    lastname: "Smith",
    email: "bob.smith@example.com",
    role: "Developer",
    status: "Active",
    agency: "Agency B",
    department: "IT",
    dateHired: "2020-07-22",
  },
  {
    id: "3",
    qrCode: "QR003",
    firstName: "Charlie",
    lastname: "Lee",
    email: "charlie.lee@example.com",
    role: "Analyst",
    status: "Inactive",
    agency: "Agency C",
    department: "Finance",
    dateHired: "2019-01-10",
  },
  {
    id: "4",
    qrCode: "QR004",
    firstName: "Diana",
    lastname: "Moore",
    email: "diana.moore@example.com",
    role: "Consultant",
    status: "Active",
    agency: "Agency A",
    department: "HR",
    dateHired: "2022-04-19",
  },
  {
    id: "5",
    qrCode: "QR005",
    firstName: "Ethan",
    lastname: "Garcia",
    email: "ethan.garcia@example.com",
    role: "Engineer",
    status: "Active",
    agency: "Agency B",
    department: "IT",
    dateHired: "2018-11-30",
  },
  {
    id: "6",
    qrCode: "QR006",
    firstName: "Fiona",
    lastname: "Wright",
    email: "fiona.wright@example.com",
    role: "Coordinator",
    status: "Inactive",
    agency: "Agency C",
    department: "Logistics",
    dateHired: "2023-02-08",
  },
  {
    id: "7",
    qrCode: "QR007",
    firstName: "George",
    lastname: "Adams",
    email: "george.adams@example.com",
    role: "Manager",
    status: "Active",
    agency: "Agency D",
    department: "Sales",
    dateHired: "2017-09-05",
  },
  {
    id: "8",
    qrCode: "QR008",
    firstName: "Hannah",
    lastname: "Clark",
    email: "hannah.clark@example.com",
    role: "Executive",
    status: "Active",
    agency: "Agency E",
    department: "Marketing",
    dateHired: "2021-06-01",
  },
  {
    id: "9",
    qrCode: "QR009",
    firstName: "Ian",
    lastname: "Martinez",
    email: "ian.martinez@example.com",
    role: "Developer",
    status: "Inactive",
    agency: "Agency F",
    department: "IT",
    dateHired: "2016-12-12",
  },
  {
    id: "10",
    qrCode: "QR010",
    firstName: "Julia",
    lastname: "Rodriguez",
    email: "julia.rodriguez@example.com",
    role: "Analyst",
    status: "Active",
    agency: "Agency G",
    department: "Finance",
    dateHired: "2020-10-23",
  },
  {
    id: "11",
    qrCode: "QR011",
    firstName: "Kevin",
    lastname: "Lewis",
    email: "kevin.lewis@example.com",
    role: "Engineer",
    status: "Active",
    agency: "Agency H",
    department: "Operations",
    dateHired: "2021-02-14",
  },
  {
    id: "12",
    qrCode: "QR012",
    firstName: "Laura",
    lastname: "Walker",
    email: "laura.walker@example.com",
    role: "Manager",
    status: "Inactive",
    agency: "Agency I",
    department: "Logistics",
    dateHired: "2019-08-17",
  },
  {
    id: "13",
    qrCode: "QR013",
    firstName: "Mike",
    lastname: "Hall",
    email: "mike.hall@example.com",
    role: "Consultant",
    status: "Active",
    agency: "Agency J",
    department: "HR",
    dateHired: "2018-05-28",
  },
  {
    id: "14",
    qrCode: "QR014",
    firstName: "Nina",
    lastname: "Allen",
    email: "nina.allen@example.com",
    role: "Executive",
    status: "Active",
    agency: "Agency K",
    department: "Marketing",
    dateHired: "2023-01-04",
  },
  {
    id: "15",
    qrCode: "QR015",
    firstName: "Oscar",
    lastname: "Young",
    email: "oscar.young@example.com",
    role: "Analyst",
    status: "Inactive",
    agency: "Agency L",
    department: "Finance",
    dateHired: "2020-04-30",
  },
  {
    id: "16",
    qrCode: "QR016",
    firstName: "Paula",
    lastname: "Hernandez",
    email: "paula.hernandez@example.com",
    role: "Coordinator",
    status: "Active",
    agency: "Agency M",
    department: "Sales",
    dateHired: "2017-11-09",
  },
  {
    id: "17",
    qrCode: "QR017",
    firstName: "Quentin",
    lastname: "King",
    email: "quentin.king@example.com",
    role: "Engineer",
    status: "Active",
    agency: "Agency N",
    department: "IT",
    dateHired: "2021-09-11",
  },
  {
    id: "18",
    qrCode: "QR018",
    firstName: "Rachel",
    lastname: "Scott",
    email: "rachel.scott@example.com",
    role: "Developer",
    status: "Inactive",
    agency: "Agency O",
    department: "Development",
    dateHired: "2022-03-03",
  },
  {
    id: "19",
    qrCode: "QR019",
    firstName: "Steve",
    lastname: "Baker",
    email: "steve.baker@example.com",
    role: "Manager",
    status: "Active",
    agency: "Agency P",
    department: "Operations",
    dateHired: "2020-12-20",
  },
  {
    id: "20",
    qrCode: "QR020",
    firstName: "Tina",
    lastname: "Carter",
    email: "tina.carter@example.com",
    role: "Executive",
    status: "Active",
    agency: "Agency Q",
    department: "Marketing",
    dateHired: "2021-07-18",
  },
]

function UsersPage() {
  return (
    <>
      <section>
        <h1 className='text-4xl font-bold'>Users</h1>
      </section>

      <section>
        <DataTable columns={columns} data={testUsers} />
      </section>
    </>
  )
}

export default UsersPage